name: BoxTradeStick
version: '${projectVersion}'
main: net.okocraft.boxtradestick.BoxTradeStickPlugin
api-version: 1.19
folia-supported: true
depend:
  - Box

permissions:
  boxtradestick.trade:
    default: true
